version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  backend:
    build: ./HealthCheckAPI
    ports:
      - "7057:80"
    environment:
      - ConnectionStrings__SqlServerConnection=Server=db;Database=HealthCheckDb;User Id=sa;Password=YourStrong!Passw0rd;
    depends_on:
      - db

  frontend:
    build: ./Frontend
    ports:
      - "3003:80"
    depends_on:
      - backend
